apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulselog-backend
  namespace: pulselog
  labels:
    app.kubernetes.io/name: pulselog-backend
    app.kubernetes.io/part-of: pulselog
    app.kubernetes.io/component: backend
# Backend does not need to talk to K8s API
# Vault annotation will be added here later for secret injection
automountServiceAccountToken: false
