apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulselog-postgres
  namespace: pulselog
  labels:
    app.kubernetes.io/name: pulselog-postgres
    app.kubernetes.io/part-of: pulselog
    app.kubernetes.io/component: database
# Postgres does not need to talk to K8s API
# disabling token mount = smaller attack surface
automountServiceAccountToken: false
